// Code generated by protoc-gen-go. DO NOT EDIT.
// source: doogle.proto

package doogle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type StringMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{1}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NodeInfo struct {
	DoogleAddress        []byte   `protobuf:"bytes,1,opt,name=doogleAddress,proto3" json:"doogleAddress,omitempty"`
	NetworkAddress       string   `protobuf:"bytes,2,opt,name=networkAddress,proto3" json:"networkAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{2}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetDoogleAddress() []byte {
	if m != nil {
		return m.DoogleAddress
	}
	return nil
}

func (m *NodeInfo) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

type NodeInfos struct {
	Infos                []*NodeInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NodeInfos) Reset()         { *m = NodeInfos{} }
func (m *NodeInfos) String() string { return proto.CompactTextString(m) }
func (*NodeInfos) ProtoMessage()    {}
func (*NodeInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{3}
}

func (m *NodeInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfos.Unmarshal(m, b)
}
func (m *NodeInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfos.Marshal(b, m, deterministic)
}
func (m *NodeInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfos.Merge(m, src)
}
func (m *NodeInfos) XXX_Size() int {
	return xxx_messageInfo_NodeInfos.Size(m)
}
func (m *NodeInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfos.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfos proto.InternalMessageInfo

func (m *NodeInfos) GetInfos() []*NodeInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type NodeCertificate struct {
	DoogleAddress        []byte   `protobuf:"bytes,1,opt,name=doogleAddress,proto3" json:"doogleAddress,omitempty"`
	NetworkAddress       string   `protobuf:"bytes,2,opt,name=networkAddress,proto3" json:"networkAddress,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Nonce                []byte   `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Difficulty           int32    `protobuf:"varint,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeCertificate) Reset()         { *m = NodeCertificate{} }
func (m *NodeCertificate) String() string { return proto.CompactTextString(m) }
func (*NodeCertificate) ProtoMessage()    {}
func (*NodeCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{4}
}

func (m *NodeCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCertificate.Unmarshal(m, b)
}
func (m *NodeCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCertificate.Marshal(b, m, deterministic)
}
func (m *NodeCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCertificate.Merge(m, src)
}
func (m *NodeCertificate) XXX_Size() int {
	return xxx_messageInfo_NodeCertificate.Size(m)
}
func (m *NodeCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCertificate proto.InternalMessageInfo

func (m *NodeCertificate) GetDoogleAddress() []byte {
	if m != nil {
		return m.DoogleAddress
	}
	return nil
}

func (m *NodeCertificate) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

func (m *NodeCertificate) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *NodeCertificate) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *NodeCertificate) GetDifficulty() int32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

type StoreItemRequest struct {
	Certificate          *NodeCertificate `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Url                  string           `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title                string           `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	EdgeURLs             []string         `protobuf:"bytes,5,rep,name=edgeURLs,proto3" json:"edgeURLs,omitempty"`
	Index                string           `protobuf:"bytes,6,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StoreItemRequest) Reset()         { *m = StoreItemRequest{} }
func (m *StoreItemRequest) String() string { return proto.CompactTextString(m) }
func (*StoreItemRequest) ProtoMessage()    {}
func (*StoreItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{5}
}

func (m *StoreItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreItemRequest.Unmarshal(m, b)
}
func (m *StoreItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreItemRequest.Marshal(b, m, deterministic)
}
func (m *StoreItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreItemRequest.Merge(m, src)
}
func (m *StoreItemRequest) XXX_Size() int {
	return xxx_messageInfo_StoreItemRequest.Size(m)
}
func (m *StoreItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreItemRequest proto.InternalMessageInfo

func (m *StoreItemRequest) GetCertificate() *NodeCertificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *StoreItemRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *StoreItemRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StoreItemRequest) GetEdgeURLs() []string {
	if m != nil {
		return m.EdgeURLs
	}
	return nil
}

func (m *StoreItemRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type Item struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	LocalRank            float64  `protobuf:"fixed64,4,opt,name=localRank,proto3" json:"localRank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{6}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetLocalRank() float64 {
	if m != nil {
		return m.LocalRank
	}
	return 0
}

type Items struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{7}
}

func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type FindIndexRequest struct {
	Certificate          *NodeCertificate `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	DoogleAddress        string           `protobuf:"bytes,2,opt,name=doogleAddress,proto3" json:"doogleAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FindIndexRequest) Reset()         { *m = FindIndexRequest{} }
func (m *FindIndexRequest) String() string { return proto.CompactTextString(m) }
func (*FindIndexRequest) ProtoMessage()    {}
func (*FindIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{8}
}

func (m *FindIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindIndexRequest.Unmarshal(m, b)
}
func (m *FindIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindIndexRequest.Marshal(b, m, deterministic)
}
func (m *FindIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindIndexRequest.Merge(m, src)
}
func (m *FindIndexRequest) XXX_Size() int {
	return xxx_messageInfo_FindIndexRequest.Size(m)
}
func (m *FindIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindIndexRequest proto.InternalMessageInfo

func (m *FindIndexRequest) GetCertificate() *NodeCertificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *FindIndexRequest) GetDoogleAddress() string {
	if m != nil {
		return m.DoogleAddress
	}
	return ""
}

type FindIndexReply struct {
	// Types that are valid to be assigned to Result:
	//	*FindIndexReply_NodeInfos
	//	*FindIndexReply_Items
	Result               isFindIndexReply_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FindIndexReply) Reset()         { *m = FindIndexReply{} }
func (m *FindIndexReply) String() string { return proto.CompactTextString(m) }
func (*FindIndexReply) ProtoMessage()    {}
func (*FindIndexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{9}
}

func (m *FindIndexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindIndexReply.Unmarshal(m, b)
}
func (m *FindIndexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindIndexReply.Marshal(b, m, deterministic)
}
func (m *FindIndexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindIndexReply.Merge(m, src)
}
func (m *FindIndexReply) XXX_Size() int {
	return xxx_messageInfo_FindIndexReply.Size(m)
}
func (m *FindIndexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindIndexReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindIndexReply proto.InternalMessageInfo

type isFindIndexReply_Result interface {
	isFindIndexReply_Result()
}

type FindIndexReply_NodeInfos struct {
	NodeInfos *NodeInfos `protobuf:"bytes,1,opt,name=nodeInfos,proto3,oneof"`
}

type FindIndexReply_Items struct {
	Items *Items `protobuf:"bytes,2,opt,name=items,proto3,oneof"`
}

func (*FindIndexReply_NodeInfos) isFindIndexReply_Result() {}

func (*FindIndexReply_Items) isFindIndexReply_Result() {}

func (m *FindIndexReply) GetResult() isFindIndexReply_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *FindIndexReply) GetNodeInfos() *NodeInfos {
	if x, ok := m.GetResult().(*FindIndexReply_NodeInfos); ok {
		return x.NodeInfos
	}
	return nil
}

func (m *FindIndexReply) GetItems() *Items {
	if x, ok := m.GetResult().(*FindIndexReply_Items); ok {
		return x.Items
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FindIndexReply) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FindIndexReply_OneofMarshaler, _FindIndexReply_OneofUnmarshaler, _FindIndexReply_OneofSizer, []interface{}{
		(*FindIndexReply_NodeInfos)(nil),
		(*FindIndexReply_Items)(nil),
	}
}

func _FindIndexReply_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FindIndexReply)
	// result
	switch x := m.Result.(type) {
	case *FindIndexReply_NodeInfos:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NodeInfos); err != nil {
			return err
		}
	case *FindIndexReply_Items:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Items); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FindIndexReply.Result has unexpected type %T", x)
	}
	return nil
}

func _FindIndexReply_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FindIndexReply)
	switch tag {
	case 1: // result.nodeInfos
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NodeInfos)
		err := b.DecodeMessage(msg)
		m.Result = &FindIndexReply_NodeInfos{msg}
		return true, err
	case 2: // result.items
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Items)
		err := b.DecodeMessage(msg)
		m.Result = &FindIndexReply_Items{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FindIndexReply_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FindIndexReply)
	// result
	switch x := m.Result.(type) {
	case *FindIndexReply_NodeInfos:
		s := proto.Size(x.NodeInfos)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FindIndexReply_Items:
		s := proto.Size(x.Items)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FindNodeRequest struct {
	Certificate          *NodeCertificate `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	DoogleAddress        []byte           `protobuf:"bytes,2,opt,name=doogleAddress,proto3" json:"doogleAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FindNodeRequest) Reset()         { *m = FindNodeRequest{} }
func (m *FindNodeRequest) String() string { return proto.CompactTextString(m) }
func (*FindNodeRequest) ProtoMessage()    {}
func (*FindNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{10}
}

func (m *FindNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNodeRequest.Unmarshal(m, b)
}
func (m *FindNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNodeRequest.Marshal(b, m, deterministic)
}
func (m *FindNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNodeRequest.Merge(m, src)
}
func (m *FindNodeRequest) XXX_Size() int {
	return xxx_messageInfo_FindNodeRequest.Size(m)
}
func (m *FindNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindNodeRequest proto.InternalMessageInfo

func (m *FindNodeRequest) GetCertificate() *NodeCertificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *FindNodeRequest) GetDoogleAddress() []byte {
	if m != nil {
		return m.DoogleAddress
	}
	return nil
}

type GetIndexReply struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndexReply) Reset()         { *m = GetIndexReply{} }
func (m *GetIndexReply) String() string { return proto.CompactTextString(m) }
func (*GetIndexReply) ProtoMessage()    {}
func (*GetIndexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_947ca98c6f36e503, []int{11}
}

func (m *GetIndexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexReply.Unmarshal(m, b)
}
func (m *GetIndexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexReply.Marshal(b, m, deterministic)
}
func (m *GetIndexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexReply.Merge(m, src)
}
func (m *GetIndexReply) XXX_Size() int {
	return xxx_messageInfo_GetIndexReply.Size(m)
}
func (m *GetIndexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexReply proto.InternalMessageInfo

func (m *GetIndexReply) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "doogle.Empty")
	proto.RegisterType((*StringMessage)(nil), "doogle.StringMessage")
	proto.RegisterType((*NodeInfo)(nil), "doogle.NodeInfo")
	proto.RegisterType((*NodeInfos)(nil), "doogle.NodeInfos")
	proto.RegisterType((*NodeCertificate)(nil), "doogle.NodeCertificate")
	proto.RegisterType((*StoreItemRequest)(nil), "doogle.StoreItemRequest")
	proto.RegisterType((*Item)(nil), "doogle.Item")
	proto.RegisterType((*Items)(nil), "doogle.Items")
	proto.RegisterType((*FindIndexRequest)(nil), "doogle.FindIndexRequest")
	proto.RegisterType((*FindIndexReply)(nil), "doogle.FindIndexReply")
	proto.RegisterType((*FindNodeRequest)(nil), "doogle.FindNodeRequest")
	proto.RegisterType((*GetIndexReply)(nil), "doogle.GetIndexReply")
}

func init() { proto.RegisterFile("doogle.proto", fileDescriptor_947ca98c6f36e503) }

var fileDescriptor_947ca98c6f36e503 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5f, 0x6f, 0x12, 0x41,
	0x10, 0xf7, 0x80, 0x3b, 0xb8, 0x01, 0x5a, 0x5c, 0xff, 0xf4, 0x42, 0x1a, 0x43, 0x36, 0x6a, 0x30,
	0x26, 0x35, 0x85, 0xc6, 0xe8, 0x83, 0x0f, 0xfe, 0xa9, 0x4a, 0xac, 0xa6, 0xd9, 0xda, 0xe8, 0x2b,
	0xbd, 0x5b, 0x70, 0xd3, 0xe3, 0x16, 0x6f, 0x97, 0x28, 0x9f, 0xc8, 0x0f, 0xe0, 0x17, 0xf1, 0x23,
	0x99, 0xdd, 0x63, 0xb9, 0xe5, 0x80, 0xe8, 0x43, 0xfb, 0xb6, 0x33, 0xf3, 0x9b, 0x3f, 0xbf, 0x99,
	0xc9, 0x2c, 0x34, 0x22, 0xce, 0xc7, 0x31, 0x3d, 0x98, 0xa6, 0x5c, 0x72, 0xe4, 0x65, 0x12, 0xae,
	0x82, 0x7b, 0x3c, 0x99, 0xca, 0x39, 0x7e, 0x04, 0xcd, 0x33, 0x99, 0xb2, 0x64, 0xfc, 0x91, 0x0a,
	0x31, 0x1c, 0x53, 0x14, 0x40, 0x75, 0x92, 0x3d, 0x03, 0xa7, 0xe3, 0x74, 0x7d, 0x62, 0x44, 0xfc,
	0x15, 0x6a, 0x9f, 0x78, 0x44, 0x07, 0xc9, 0x88, 0xa3, 0xfb, 0xd0, 0xcc, 0x22, 0xbd, 0x8c, 0xa2,
	0x94, 0x0a, 0xa1, 0xb1, 0x0d, 0xb2, 0xaa, 0x44, 0x0f, 0x61, 0x27, 0xa1, 0xf2, 0x07, 0x4f, 0x2f,
	0x0d, 0xac, 0xa4, 0x43, 0x16, 0xb4, 0xb8, 0x0f, 0xbe, 0x89, 0xac, 0x9c, 0x5c, 0xa6, 0x1e, 0x81,
	0xd3, 0x29, 0x77, 0xeb, 0xbd, 0xd6, 0xc1, 0x82, 0x80, 0x41, 0x90, 0xcc, 0x8c, 0x7f, 0x3b, 0xb0,
	0xab, 0x74, 0xaf, 0x69, 0x2a, 0xd9, 0x88, 0x85, 0x43, 0x49, 0xaf, 0xb6, 0x2c, 0xb4, 0x0f, 0xfe,
	0x74, 0x76, 0x11, 0xb3, 0xf0, 0x03, 0x9d, 0x07, 0x65, 0x1d, 0x29, 0x57, 0xa0, 0xdb, 0xe0, 0x26,
	0x3c, 0x09, 0x69, 0x50, 0xd1, 0x96, 0x4c, 0x40, 0xf7, 0x00, 0x22, 0x36, 0x1a, 0xb1, 0x70, 0x16,
	0xcb, 0x79, 0xe0, 0x76, 0x9c, 0xae, 0x4b, 0x2c, 0x0d, 0xfe, 0xe5, 0x40, 0xeb, 0x4c, 0xf2, 0x94,
	0x0e, 0x24, 0x9d, 0x10, 0xfa, 0x7d, 0x46, 0x85, 0x44, 0xcf, 0xa1, 0x1e, 0xe6, 0x2c, 0x74, 0xd1,
	0xf5, 0xde, 0x9e, 0x4d, 0xdc, 0x22, 0x49, 0x6c, 0x2c, 0x6a, 0x41, 0x79, 0x96, 0xc6, 0x0b, 0x02,
	0xea, 0xa9, 0xea, 0x92, 0x4c, 0xc6, 0x54, 0x57, 0xec, 0x93, 0x4c, 0x40, 0x6d, 0xa8, 0xd1, 0x68,
	0x4c, 0xcf, 0xc9, 0x89, 0x08, 0xdc, 0x4e, 0xb9, 0xeb, 0x93, 0xa5, 0xac, 0x3c, 0x58, 0x12, 0xd1,
	0x9f, 0x81, 0x97, 0x79, 0x68, 0x01, 0x9f, 0x40, 0x45, 0xd5, 0x68, 0x32, 0x38, 0x1b, 0x32, 0x94,
	0xec, 0x0c, 0xfb, 0xe0, 0xc7, 0x3c, 0x1c, 0xc6, 0x64, 0x98, 0x5c, 0xea, 0x9e, 0x38, 0x24, 0x57,
	0xe0, 0xc7, 0xe0, 0xaa, 0x68, 0x02, 0x61, 0x70, 0x99, 0x7a, 0x2c, 0xc6, 0xdb, 0x30, 0x2c, 0x75,
	0x3f, 0x32, 0x13, 0x16, 0xd0, 0x7a, 0xcb, 0x92, 0x68, 0xa0, 0xea, 0xb8, 0x82, 0x1e, 0xad, 0x6d,
	0x45, 0x56, 0xf7, 0xaa, 0x12, 0x4b, 0xd8, 0xb1, 0x92, 0x4e, 0xe3, 0x39, 0x3a, 0x04, 0x3f, 0x31,
	0x6b, 0xb9, 0x48, 0x78, 0xb3, 0xb8, 0x8d, 0xe2, 0xfd, 0x0d, 0x92, 0xa3, 0xd0, 0x03, 0xc3, 0xae,
	0xa4, 0xe1, 0x4d, 0x9b, 0x9d, 0x82, 0x66, 0xd6, 0x57, 0x35, 0xf0, 0x52, 0x2a, 0x66, 0xb1, 0xc4,
	0x29, 0xec, 0xaa, 0xac, 0x2a, 0xdc, 0x75, 0x31, 0x2d, 0xee, 0x3f, 0xee, 0x43, 0xf3, 0x1d, 0x95,
	0x16, 0xd1, 0xff, 0x98, 0x49, 0xef, 0x4f, 0x19, 0xbc, 0x37, 0x5a, 0x8d, 0x8e, 0xc0, 0x5f, 0xae,
	0x30, 0x0a, 0x0c, 0xb8, 0xb8, 0xd5, 0xed, 0x25, 0x79, 0x7d, 0x69, 0xd0, 0x0b, 0xf0, 0x97, 0xfd,
	0xcd, 0xbd, 0x8a, 0x73, 0x6e, 0xdf, 0xdd, 0x60, 0x51, 0x35, 0x3e, 0x85, 0x9a, 0x69, 0x14, 0xda,
	0xb3, 0x31, 0x56, 0xeb, 0xda, 0xeb, 0xe3, 0x41, 0xc7, 0x70, 0xeb, 0x94, 0x25, 0xe3, 0x2f, 0x4c,
	0x7e, 0xb3, 0x2f, 0xc5, 0xb6, 0x7e, 0xb6, 0xef, 0xe4, 0x7c, 0xec, 0xb3, 0x78, 0x04, 0x15, 0x15,
	0x06, 0x6d, 0x36, 0x6f, 0xf3, 0x3a, 0x04, 0x4f, 0x79, 0x7d, 0xe6, 0x68, 0xed, 0x8c, 0x6d, 0x73,
	0x79, 0x06, 0x35, 0x33, 0x9c, 0x7f, 0x26, 0x5b, 0x9d, 0xe2, 0x13, 0xa8, 0x9e, 0x72, 0x21, 0xcf,
	0xd3, 0x78, 0x9b, 0xe3, 0xea, 0x44, 0x2e, 0x3c, 0xfd, 0x27, 0xf4, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0x73, 0x59, 0x5e, 0x23, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DoogleClient is the client API for Doogle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DoogleClient interface {
	// Store give index
	StoreItem(ctx context.Context, in *StoreItemRequest, opts ...grpc.CallOption) (*Empty, error)
	// find index of given key
	FindIndex(ctx context.Context, in *FindIndexRequest, opts ...grpc.CallOption) (*FindIndexReply, error)
	// return k closed nodes to given address
	FindNode(ctx context.Context, in *FindNodeRequest, opts ...grpc.CallOption) (*NodeInfos, error)
	// health check
	PingWithCertificate(ctx context.Context, in *NodeCertificate, opts ...grpc.CallOption) (*StringMessage, error)
	// the following endpoints can be accessed from outside of the network.
	Ping(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
	PingTo(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*StringMessage, error)
	GetIndex(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*GetIndexReply, error)
	PostUrl(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Empty, error)
}

type doogleClient struct {
	cc *grpc.ClientConn
}

func NewDoogleClient(cc *grpc.ClientConn) DoogleClient {
	return &doogleClient{cc}
}

func (c *doogleClient) StoreItem(ctx context.Context, in *StoreItemRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/StoreItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doogleClient) FindIndex(ctx context.Context, in *FindIndexRequest, opts ...grpc.CallOption) (*FindIndexReply, error) {
	out := new(FindIndexReply)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/FindIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doogleClient) FindNode(ctx context.Context, in *FindNodeRequest, opts ...grpc.CallOption) (*NodeInfos, error) {
	out := new(NodeInfos)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/FindNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doogleClient) PingWithCertificate(ctx context.Context, in *NodeCertificate, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/PingWithCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doogleClient) Ping(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doogleClient) PingTo(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/PingTo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doogleClient) GetIndex(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*GetIndexReply, error) {
	out := new(GetIndexReply)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/GetIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doogleClient) PostUrl(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/doogle.Doogle/PostUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoogleServer is the server API for Doogle service.
type DoogleServer interface {
	// Store give index
	StoreItem(context.Context, *StoreItemRequest) (*Empty, error)
	// find index of given key
	FindIndex(context.Context, *FindIndexRequest) (*FindIndexReply, error)
	// return k closed nodes to given address
	FindNode(context.Context, *FindNodeRequest) (*NodeInfos, error)
	// health check
	PingWithCertificate(context.Context, *NodeCertificate) (*StringMessage, error)
	// the following endpoints can be accessed from outside of the network.
	Ping(context.Context, *StringMessage) (*StringMessage, error)
	PingTo(context.Context, *NodeInfo) (*StringMessage, error)
	GetIndex(context.Context, *StringMessage) (*GetIndexReply, error)
	PostUrl(context.Context, *StringMessage) (*Empty, error)
}

func RegisterDoogleServer(s *grpc.Server, srv DoogleServer) {
	s.RegisterService(&_Doogle_serviceDesc, srv)
}

func _Doogle_StoreItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).StoreItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/StoreItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).StoreItem(ctx, req.(*StoreItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doogle_FindIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).FindIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/FindIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).FindIndex(ctx, req.(*FindIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doogle_FindNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).FindNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/FindNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).FindNode(ctx, req.(*FindNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doogle_PingWithCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeCertificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).PingWithCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/PingWithCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).PingWithCertificate(ctx, req.(*NodeCertificate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doogle_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).Ping(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doogle_PingTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).PingTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/PingTo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).PingTo(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doogle_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/GetIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).GetIndex(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doogle_PostUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoogleServer).PostUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doogle.Doogle/PostUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoogleServer).PostUrl(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Doogle_serviceDesc = grpc.ServiceDesc{
	ServiceName: "doogle.Doogle",
	HandlerType: (*DoogleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreItem",
			Handler:    _Doogle_StoreItem_Handler,
		},
		{
			MethodName: "FindIndex",
			Handler:    _Doogle_FindIndex_Handler,
		},
		{
			MethodName: "FindNode",
			Handler:    _Doogle_FindNode_Handler,
		},
		{
			MethodName: "PingWithCertificate",
			Handler:    _Doogle_PingWithCertificate_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Doogle_Ping_Handler,
		},
		{
			MethodName: "PingTo",
			Handler:    _Doogle_PingTo_Handler,
		},
		{
			MethodName: "GetIndex",
			Handler:    _Doogle_GetIndex_Handler,
		},
		{
			MethodName: "PostUrl",
			Handler:    _Doogle_PostUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doogle.proto",
}
